server:
 port: 8090

keystore:
 password: mySecretKey
spring:
  application:
    name: auth-service
  cloud:
    config:
      server:
        git:
          uri: http://localhost:8888/
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://18.217.130.9:8761/eureka/
      
  datasource:
   tomcat:
     initial-size: 2  
  mvc:
    dispatchOptionsRequest: true